" Name:         Corvine
" Description:  A dark, low-contrast colourscheme inspired by Raven and Apprentice
" Author:       Aramis Razzaghipour <aramisnoah@gmail.com>
" Maintainer:   Aramis Razzaghipour <aramisnoah@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: Mon  2 Sep 12:26:08 2019

" Generated by Colortemplate v2.0.0

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'corvine'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262626', '#d78787', '#5faf87', '#d7d7af',
        \ '#87afd7', '#afafd7', '#87d7d7', '#c6c6c6', '#626262', '#ffafaf',
        \ '#87d7af', '#d7d787', '#87d7ff', '#d7afd7', '#5fd7d7', '#eeeeee']
  if has('nvim')
    let g:terminal_color_0 = '#262626'
    let g:terminal_color_1 = '#d78787'
    let g:terminal_color_2 = '#5faf87'
    let g:terminal_color_3 = '#d7d7af'
    let g:terminal_color_4 = '#87afd7'
    let g:terminal_color_5 = '#afafd7'
    let g:terminal_color_6 = '#87d7d7'
    let g:terminal_color_7 = '#c6c6c6'
    let g:terminal_color_8 = '#626262'
    let g:terminal_color_9 = '#ffafaf'
    let g:terminal_color_10 = '#87d7af'
    let g:terminal_color_11 = '#d7d787'
    let g:terminal_color_12 = '#87d7ff'
    let g:terminal_color_13 = '#d7afd7'
    let g:terminal_color_14 = '#5fd7d7'
    let g:terminal_color_15 = '#eeeeee'
  endif
  hi Normal guifg=#c6c6c6 guibg=#121212 guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#121212 guibg=#eeeeee guisp=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#c6c6c6 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#626262 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#626262 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#626262 guibg=#080808 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#eeeeee guibg=#3a3a3a guisp=NONE gui=bold cterm=bold
  hi SignColumn guifg=#626262 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#585858 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#080808 guibg=#080808 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#eeeeee guibg=#3a3a3a guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#585858 guibg=#585858 guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#121212 guibg=#d78787 guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#5faf87 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#d7d787 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#d7d787 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#d78787 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=#121212 guibg=#d7d787 guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#c6c6c6 guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#626262 guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#1c1c1c guibg=#1c1c1c guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#eeeeee guibg=#626262 guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#121212 guibg=#d78700 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#121212 guibg=#d7af00 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#262626 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#121212 guibg=#5faf87 guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffDelete guifg=#121212 guibg=#d78787 guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#121212 guibg=#d78700 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#626262 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#d7d787 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#121212 guibg=#d78787 guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#d7afd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#5faf87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#d78787 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#87afd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#afafd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#87d7d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#d7afd7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#d7d7af guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#eeeeee guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#eeeeee guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Underlined guifg=#87d7ff guibg=NONE guisp=NONE gui=underline cterm=underline
  hi SpellBad guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi markdownBold guifg=#d78700 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi markdownItalic guifg=#d78700 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Float Number
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Operator Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link SpecialComment Todo
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Searchlight IncSearch
  hi! link gitcommitOverflow Error
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link markdownLinkDelimiter Delimiter
  hi! link markdownLinkTextDelimiter Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link helpHyperTextJump Underlined
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimHighlight Statement
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi markdownItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  hi Normal ctermfg=251 ctermbg=233 cterm=NONE
  if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
    set background=dark
  endif
  hi Cursor ctermfg=233 ctermbg=255 cterm=NONE
  hi CursorLineNr ctermfg=251 ctermbg=234 cterm=NONE
  hi FoldColumn ctermfg=241 ctermbg=234 cterm=NONE
  hi Folded ctermfg=241 ctermbg=234 cterm=NONE
  hi LineNr ctermfg=241 ctermbg=232 cterm=NONE
  hi MatchParen ctermfg=255 ctermbg=237 cterm=bold
  hi SignColumn ctermfg=241 ctermbg=234 cterm=NONE
  hi Ignore ctermfg=240 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=251 ctermbg=235 cterm=NONE
  hi PmenuSbar ctermfg=232 ctermbg=232 cterm=NONE
  hi PmenuSel ctermfg=255 ctermbg=237 cterm=NONE
  hi PmenuThumb ctermfg=240 ctermbg=240 cterm=NONE
  hi ErrorMsg ctermfg=233 ctermbg=174 cterm=NONE
  hi ModeMsg ctermfg=72 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=186 ctermbg=NONE cterm=NONE
  hi Question ctermfg=186 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=174 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=234 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=234 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=234 cterm=NONE
  hi QuickFixLine ctermfg=233 ctermbg=186 cterm=NONE
  hi StatusLine ctermfg=251 ctermbg=235 cterm=NONE
  hi StatusLineNC ctermfg=241 ctermbg=234 cterm=NONE
  hi VertSplit ctermfg=234 ctermbg=234 cterm=NONE
  hi WildMenu ctermfg=255 ctermbg=241 cterm=NONE
  hi IncSearch ctermfg=233 ctermbg=172 cterm=NONE
  hi Search ctermfg=233 ctermbg=178 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=235 cterm=NONE
  hi DiffAdd ctermfg=233 ctermbg=72 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=NONE cterm=NONE
  hi DiffDelete ctermfg=233 ctermbg=174 cterm=NONE
  hi DiffText ctermfg=233 ctermbg=172 cterm=NONE
  hi Comment ctermfg=241 ctermbg=NONE cterm=italic
  hi Constant ctermfg=186 ctermbg=NONE cterm=NONE
  hi Error ctermfg=233 ctermbg=174 cterm=NONE
  hi Identifier ctermfg=182 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=72 ctermbg=NONE cterm=NONE
  hi Special ctermfg=174 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=110 ctermbg=NONE cterm=NONE
  hi Type ctermfg=146 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=246 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=116 ctermbg=NONE cterm=NONE
  hi Function ctermfg=182 ctermbg=NONE cterm=NONE
  hi String ctermfg=187 ctermbg=NONE cterm=NONE
  hi Title ctermfg=255 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=255 ctermbg=NONE cterm=bold
  hi Underlined ctermfg=117 ctermbg=NONE cterm=underline
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi markdownBold ctermfg=172 ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=172 ctermbg=NONE cterm=italic
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Float Number
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Operator Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link SpecialComment Todo
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Searchlight IncSearch
  hi! link gitcommitOverflow Error
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link markdownLinkDelimiter Delimiter
  hi! link markdownLinkTextDelimiter Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link helpHyperTextJump Underlined
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimHighlight Statement
  if !s:italics
    hi Comment cterm=NONE
    hi markdownItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: dark_back     #080808 ~
" Color: back          #121212 ~
" Color: faded_back    #1c1c1c ~
" Color: grey          #262626 ~
" Color: light_grey    #3a3a3a ~
" Color: dark_fore     #585858 ~
" Color: faded_fore    #626262 ~
" Color: low_fore      #949494 ~
" Color: fore          #c6c6c6 ~
" Color: white         #eeeeee ~
" Color: aqua          #5fd7d7 ~
" Color: blue          #87d7ff ~
" Color: dark_aqua     #87d7d7 ~
" Color: dark_blue     #87afd7 ~
" Color: dark_green    #5faf87 ~
" Color: dark_purple   #afafd7 ~
" Color: dark_red      #d78787 ~
" Color: dark_yellow   #d7d7af ~
" Color: green         #87d7af ~
" Color: orange        #d78700 ~
" Color: purple        #d7afd7 ~
" Color: red           #ffafaf ~
" Color: strong_yellow #d7af00 ~
" Color: yellow        #d7d787 ~
" Term colors: grey       dark_red    dark_green dark_yellow
" Term colors: dark_blue  dark_purple dark_aqua  fore
" Term colors: faded_fore red         green      yellow
" Term colors: blue       purple      aqua       white
" vim: et ts=2 sw=2
