" Name:         Corvine Light
" Description:  A light, low-contrast colourscheme inspired by Raven and Apprentice
" Author:       Aramis Razzaghipour <aramisnoah@gmail.com>
" Maintainer:   Aramis Razzaghipour <aramisnoah@gmail.com>
" License:      Vim License (see `:help license`)
" Last Updated: Thu 10 Oct 13:03:00 2019

" Generated by Colortemplate v2.0.0

set background=light

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'corvine_light'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#eee8dc', '#d75f5f', '#005f00', '#af8700',
        \ '#0087d7', '#5f5faf', '#008787', '#585858', '#9e9e9e', '#d7005f',
        \ '#008700', '#af5f00', '#00afd7', '#af5faf', '#00afaf', '#000000']
  if has('nvim')
    let g:terminal_color_0 = '#eee8dc'
    let g:terminal_color_1 = '#d75f5f'
    let g:terminal_color_2 = '#005f00'
    let g:terminal_color_3 = '#af8700'
    let g:terminal_color_4 = '#0087d7'
    let g:terminal_color_5 = '#5f5faf'
    let g:terminal_color_6 = '#008787'
    let g:terminal_color_7 = '#585858'
    let g:terminal_color_8 = '#9e9e9e'
    let g:terminal_color_9 = '#d7005f'
    let g:terminal_color_10 = '#008700'
    let g:terminal_color_11 = '#af5f00'
    let g:terminal_color_12 = '#00afd7'
    let g:terminal_color_13 = '#af5faf'
    let g:terminal_color_14 = '#00afaf'
    let g:terminal_color_15 = '#000000'
  endif
  if exists('g:corvine_italics')
    let s:italics = g:corvine_italics
  endif
  hi Normal guifg=#585858 guibg=#fff9ed guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#fff9ed guibg=#000000 guisp=NONE gui=NONE cterm=NONE
  hi None guifg=NONE guibg=NONE guisp=NONE gui=NONE ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr guifg=#585858 guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#9e9e9e guibg=#f4efe4 guisp=NONE gui=NONE cterm=NONE
  hi Folded guifg=#9e9e9e guibg=#f4efe4 guisp=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#9e9e9e guibg=#f4efe4 guisp=NONE gui=NONE cterm=NONE
  hi MatchParen guifg=#000000 guibg=#f4efe4 guisp=NONE gui=bold cterm=bold
  hi SignColumn guifg=#9e9e9e guibg=#f4efe4 guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#ccc6bb guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#949494 guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#f4efe4 guibg=#f4efe4 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#000000 guibg=#e5dfd4 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#ccc6bb guibg=#ccc6bb guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#fff9ed guibg=#d75f5f guisp=NONE gui=NONE cterm=NONE
  hi ModeMsg guifg=#005f00 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi MoreMsg guifg=#af5f00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#af5f00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#d75f5f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ColorColumn guifg=NONE guibg=#f4efe4 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#f6f0e4 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#f6f0e4 guisp=NONE gui=NONE cterm=NONE
  hi QuickFixLine guifg=#fff9ed guibg=#af5f00 guisp=NONE gui=NONE cterm=NONE
  hi StatusLine guifg=#585858 guibg=#e5dfd4 guisp=NONE gui=NONE cterm=NONE
  hi StatusLineNC guifg=#949494 guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi VertSplit guifg=#eee8dc guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#000000 guibg=#9e9e9e guisp=NONE gui=NONE cterm=NONE
  hi IncSearch guifg=#fff9ed guibg=#ff5f00 guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#fff9ed guibg=#d7af00 guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=NONE guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#008700 guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi DiffChange guifg=NONE guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi DiffDelete guifg=#d75f5f guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi DiffText guifg=#af5f5f guibg=#e5dfd4 guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#9e9e9e guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#af5f00 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#fff9ed guibg=#d75f5f guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#af5faf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#008700 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#5f5f87 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#0087d7 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Type guifg=#5f5faf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Directory guifg=#008787 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#af5faf guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#af5f5f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#949494 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi String guifg=#af8700 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#585858 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Todo guifg=#000000 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=#00afd7 guibg=NONE guisp=NONE gui=underline cterm=underline
  hi SpellBad guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare guifg=NONE guibg=NONE guisp=NONE gui=undercurl ctermfg=NONE ctermbg=NONE cterm=undercurl
  if !s:italics
    hi Comment gui=NONE cterm=NONE
    hi SpecialComment gui=NONE cterm=NONE
  endif
  let g:indentLine_color_gui  = '#ccc6bb'
  let g:indentLine_color_term = 251
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Float Number
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Operator Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Searchlight IncSearch
  hi! link cssBraces Delimiter
  hi! link gitcommitOverflow Error
  hi! link gitcommitSummary Title
  hi! link helpHyperTextJump Underlined
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link scssAttribute Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimHighlight Statement
  hi! link vimUserFunc Function
  hi markdownBold guifg=NONE guibg=NONE guisp=NONE gui=bold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic guifg=NONE guibg=NONE guisp=NONE gui=italic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownUrl guifg=#9e9e9e guibg=NONE guisp=NONE gui=underline cterm=underline
  hi markdownCode guifg=NONE guibg=#eee8dc guisp=NONE gui=NONE cterm=NONE
  hi markdownFaded guifg=#9e9e9e guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi! link markdownBlockquote None
  hi! link markdownCodeBlock markdownCode
  hi! link markdownCodeDelimiter markdownCode
  hi! link markdownH1Delimiter markdownH1
  hi! link markdownH2Delimiter markdownH2
  hi! link markdownH3Delimiter markdownH3
  hi! link markdownH4Delimiter markdownH4
  hi! link markdownH5Delimiter markdownH5
  hi! link markdownH6Delimiter markdownH6
  hi! link markdownId markdownFaded
  hi! link markdownIdDeclaration markdownFaded
  hi! link markdownLinkDelimiter markdownFaded
  hi! link markdownLinkText None
  hi! link markdownLinkTextDelimiter markdownFaded
  hi! link markdownListMarker None
  hi! link markdownRule None
  if !s:italics
    hi markdownItalic gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if exists('g:corvine_italics')
    let s:italics = g:corvine_italics
  endif
  hi Normal ctermfg=240 ctermbg=231 cterm=NONE
  hi Cursor ctermfg=231 ctermbg=16 cterm=NONE
  hi None ctermfg=NONE ctermbg=NONE cterm=NONE
  hi CursorLineNr ctermfg=240 ctermbg=254 cterm=NONE
  hi FoldColumn ctermfg=247 ctermbg=255 cterm=NONE
  hi Folded ctermfg=247 ctermbg=255 cterm=NONE
  hi LineNr ctermfg=247 ctermbg=255 cterm=NONE
  hi MatchParen ctermfg=16 ctermbg=255 cterm=bold
  hi SignColumn ctermfg=247 ctermbg=255 cterm=NONE
  hi Ignore ctermfg=251 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=246 ctermbg=254 cterm=NONE
  hi PmenuSbar ctermfg=255 ctermbg=255 cterm=NONE
  hi PmenuSel ctermfg=16 ctermbg=254 cterm=NONE
  hi PmenuThumb ctermfg=251 ctermbg=251 cterm=NONE
  hi ErrorMsg ctermfg=231 ctermbg=167 cterm=NONE
  hi ModeMsg ctermfg=22 ctermbg=NONE cterm=bold
  hi MoreMsg ctermfg=130 ctermbg=NONE cterm=NONE
  hi Question ctermfg=130 ctermbg=NONE cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
  hi QuickFixLine ctermfg=231 ctermbg=130 cterm=NONE
  hi StatusLine ctermfg=240 ctermbg=254 cterm=NONE
  hi StatusLineNC ctermfg=246 ctermbg=254 cterm=NONE
  hi VertSplit ctermfg=254 ctermbg=254 cterm=NONE
  hi WildMenu ctermfg=16 ctermbg=247 cterm=NONE
  hi IncSearch ctermfg=231 ctermbg=202 cterm=NONE
  hi Search ctermfg=231 ctermbg=178 cterm=NONE
  hi Visual ctermfg=NONE ctermbg=254 cterm=NONE
  hi DiffAdd ctermfg=28 ctermbg=254 cterm=NONE
  hi DiffChange ctermfg=NONE ctermbg=254 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=254 cterm=NONE
  hi DiffText ctermfg=131 ctermbg=254 cterm=NONE
  hi Comment ctermfg=247 ctermbg=NONE cterm=italic
  hi Constant ctermfg=130 ctermbg=NONE cterm=NONE
  hi Error ctermfg=231 ctermbg=167 cterm=NONE
  hi Identifier ctermfg=133 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=28 ctermbg=NONE cterm=NONE
  hi Special ctermfg=60 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=32 ctermbg=NONE cterm=NONE
  hi Type ctermfg=61 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=246 ctermbg=NONE cterm=NONE
  hi Directory ctermfg=30 ctermbg=NONE cterm=NONE
  hi Function ctermfg=133 ctermbg=NONE cterm=NONE
  hi Number ctermfg=131 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=246 ctermbg=NONE cterm=italic
  hi String ctermfg=136 ctermbg=NONE cterm=NONE
  hi Title ctermfg=240 ctermbg=NONE cterm=bold
  hi Todo ctermfg=16 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=38 ctermbg=NONE cterm=underline
  hi SpellBad ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellCap ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellLocal ctermfg=NONE ctermbg=NONE cterm=undercurl
  hi SpellRare ctermfg=NONE ctermbg=NONE cterm=undercurl
  if !s:italics
    hi Comment cterm=NONE
    hi SpecialComment cterm=NONE
  endif
  let g:indentLine_color_gui  = '#ccc6bb'
  let g:indentLine_color_term = 251
  hi! link Terminal Normal
  hi! link TabLine StatusLineNC
  hi! link TabLineFill StatusLineNC
  hi! link TabLineSel StatusLine
  hi! link StatusLineTerm StatusLine
  hi! link StatusLineTermNC StatusLineNC
  hi! link VisualNOS Visual
  hi! link diffAdded DiffAdd
  hi! link diffBDiffer WarningMsg
  hi! link diffChanged DiffChange
  hi! link diffCommon WarningMsg
  hi! link diffDiffer WarningMsg
  hi! link diffFile Directory
  hi! link diffIdentical WarningMsg
  hi! link diffIndexLine Number
  hi! link diffIsA WarningMsg
  hi! link diffNoEOL WarningMsg
  hi! link diffOnly WarningMsg
  hi! link diffRemoved DiffDelete
  hi! link Boolean Constant
  hi! link Character Constant
  hi! link Float Number
  hi! link Conditional Statement
  hi! link Exception Statement
  hi! link Keyword Statement
  hi! link Label Statement
  hi! link Operator Statement
  hi! link Repeat Statement
  hi! link Define PreProc
  hi! link Include PreProc
  hi! link Macro PreProc
  hi! link PreCondit PreProc
  hi! link StorageClass Type
  hi! link Structure Type
  hi! link Typedef Type
  hi! link Debug Special
  hi! link SpecialChar Special
  hi! link Tag Special
  hi! link Noise Delimiter
  hi! link StringDelimiter Delimiter
  hi! link Conceal Ignore
  hi! link NonText Ignore
  hi! link SpecialKey Ignore
  hi! link EndOfBuffer Ignore
  hi! link Whitespace Ignore
  hi! link Searchlight IncSearch
  hi! link cssBraces Delimiter
  hi! link gitcommitOverflow Error
  hi! link gitcommitSummary Title
  hi! link helpHyperTextJump Underlined
  hi! link htmlEndTag Delimiter
  hi! link htmlLink Underlined
  hi! link htmlSpecialTagName htmlTagName
  hi! link htmlTag Delimiter
  hi! link htmlTagName Statement
  hi! link scssAttribute Delimiter
  hi! link vimAutoCmdSfxList Type
  hi! link vimAutoEventList Identifier
  hi! link vimCmdSep Special
  hi! link vimCommentTitle SpecialComment
  hi! link vimHighlight Statement
  hi! link vimUserFunc Function
  hi markdownBold ctermfg=NONE ctermbg=NONE cterm=bold
  hi markdownItalic ctermfg=NONE ctermbg=NONE cterm=italic
  hi markdownUrl ctermfg=247 ctermbg=NONE cterm=underline
  hi markdownCode ctermfg=NONE ctermbg=254 cterm=NONE
  hi markdownFaded ctermfg=247 ctermbg=NONE cterm=NONE
  hi! link markdownBlockquote None
  hi! link markdownCodeBlock markdownCode
  hi! link markdownCodeDelimiter markdownCode
  hi! link markdownH1Delimiter markdownH1
  hi! link markdownH2Delimiter markdownH2
  hi! link markdownH3Delimiter markdownH3
  hi! link markdownH4Delimiter markdownH4
  hi! link markdownH5Delimiter markdownH5
  hi! link markdownH6Delimiter markdownH6
  hi! link markdownId markdownFaded
  hi! link markdownIdDeclaration markdownFaded
  hi! link markdownLinkDelimiter markdownFaded
  hi! link markdownLinkText None
  hi! link markdownLinkTextDelimiter markdownFaded
  hi! link markdownListMarker None
  hi! link markdownRule None
  if !s:italics
    hi markdownItalic cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: light
" Color: base0         #f4efe4 ~
" Color: base1         #fff9ed ~
" Color: base2         #f6f0e4 ~
" Color: base3         #eee8dc ~
" Color: base4         #e5dfd4 ~
" Color: base5         #ccc6bb ~
" Color: base6         #9e9e9e ~
" Color: base7         #949494 ~
" Color: base8         #585858 ~
" Color: base9         #000000 ~
" Color: aqua          #008787 ~
" Color: blue          #0087d7 ~
" Color: dark_purple   #5f5f87 ~
" Color: green         #005f00 ~
" Color: light_aqua    #00afaf ~
" Color: light_blue    #00afd7 ~
" Color: light_green   #008700 ~
" Color: light_orange  #af5f5f ~
" Color: light_purple  #af5faf ~
" Color: light_red     #d7005f ~
" Color: light_yellow  #af5f00 ~
" Color: orange        #ff5f00 ~
" Color: purple        #5f5faf ~
" Color: red           #d75f5f ~
" Color: strong_yellow #d7af00 ~
" Color: yellow        #af8700 ~
" Term colors: base3      red          green       yellow
" Term colors: blue       purple       aqua        base8
" Term colors: base6      light_red    light_green light_yellow
" Term colors: light_blue light_purple light_aqua  base9
" vim: et ts=2 sw=2
